### ISSUE TITLE
Docs folder

### ISSUE THREAD

**Issue by oljuanfe** [Adalab/dorcas-s3-evaluacion-final-oljuanfe#4]
@nasivuela Ayer no me cargaba gitHub pages y hasta hoy no he visto que no se ha publicado correctamente el ejercicio. Me faltan la mitad de las carpetas dentro de docs. ¿Puedo, por favor, hacer un commit con los cambios para que se publique correctamente?

**Comment by nasivuela** [comment]
Dale!
